ツイートの投稿とその削除の機能を追加しました。
ayu-art/Twitclone_test pull request #3
Opened 2022-03-13 14:42 UTC by ayu-art

ツイートの投稿とその削除の機能を追加しました。

ボタンを押すとツイート画面に遷移し、ツイートすると最初の画面に戻ります。

最初の画面
![スクリーンショット (368)](https://user-images.githubusercontent.com/82298173/158064373-c03d7195-2ce5-44cd-b46b-6d4e670e022c.png)

ツイート画面
![スクリーンショット (370)](https://user-images.githubusercontent.com/82298173/158064422-923bc0f8-04d1-44db-8dc5-274bf6f788db.png)

リダイレクトした最初の画面
![スクリーンショット (371)](https://user-images.githubusercontent.com/82298173/158064429-c1d8cb0f-dc2c-4cbb-87a2-15cd60fbc56b.png)

また、自分の投稿のみ削除ボタンが表示され、ごみ箱のボタンを押すと削除モーダルが表示されます。
この削除モーダルは以下のサイトを参考に作りました。
https://blog.narito.ninja/detail/119

削除モーダル
![スクリーンショット (372)](https://user-images.githubusercontent.com/82298173/158064583-7505283c-685f-4e9e-ba18-0325ab6d81e1.png)

テストの結果はこちらです。
![スクリーンショット (367)](https://user-images.githubusercontent.com/82298173/158064826-ac2e1d23-a952-43e3-aa92-45b6ae21054c.png)

2022-03-13 15:20 UTC, ayu-art commented
あとテスト部分で分からなかった部分があったので質問させてください。（そのテスト部分は他の方法で実装できてはいます。）

一つ目
```
self.login_redirect_url = '/accounts/login/?next=/blog/tweet/'
```
ログインしていない人がログイン済みの人しか入れない画面（viewでLoginrequiredMixinに設定されているもの）に移行しようとするとログイン画面に自動的に遷移することを確認したいが、urlが "?next="が後についており、普通のログイン画面にリダイレクトされるテストにするとエラーが生じます。今回は上記のようにurlを入力して変更したのですが、他のurlは
```
self.top_url = reverse('blog:top’）
```
のようにしているのにそのままurlを指定しても大丈夫でしょうか？
<br>


二つ目
```
self.response_post = self.client.post(self.login_url, self.user_login_data)
```
ログインする時に、今回は上記のコードのようにpostしてログインさせたのですが、最初は
```
self.logined = self.client.login(username='..', password='...')
```
のようにしていました。この後にassertTrue(self.logined)でTrueになり、ログインできたと思ったのですが、ログインできておらず、その後今書いてあるテストと同じものを行ったのですが、上手くいきませんでした。具体的には、    self.response_tweet = self.client.get(self.tweet_url)　のようにしてもツイート画面にいかず、ログイン画面にリダイレクトされてしまいました。この原因がわかれば教えていただきたいです。

わかりづらくてすみません。よろしくお願い致します。

2022-03-16 02:57 UTC, kunikida007 commented
1つ目
問題ないと思います。
2つ目
https://jpcodeqa.com/q/c0b64a436e2fd62214ecfd5728355b58
こちらを参考にすれば改善すると思うのでよかったら試してみてください。

2022-03-17 08:14 UTC, ayu-art commented
ありがとうございます。
上記の方法でやってみたのですが上手くいかず、なぜか普通のloginの方でもう一度やるとうまくいったので今回はそちらでやりました。
修正しましたので他の部分と合わせて確認お願い致します！
念のためテスト結果も合わせて貼っておきます。

![スクリーンショット (373)](https://user-images.githubusercontent.com/82298173/158765511-45554652-3547-43d3-a45d-739c71e1a744.png)

2022-03-18 03:43 UTC, kunikida007 reviewed
問題ないと思います。
引きつづき頑張りましょう！

2022-03-20 13:26 UTC, Akinori13 requested changes
それぞれのテストをとても丁寧に記述していて、とてもいいです！いくつかコメントです！
- ブランチ名には、機能名（tweetなど）を含めると明示的で分かりやすいです。次回以降はお願いします。
- 不要なimportは消しちゃってください！

2022-03-20 13:26 UTC, Akinori13 commented on templates/blog/top.html
> +					<p>{{ tweet.text }}</p>
linebreaksbr

2022-03-20 13:26 UTC, Akinori13 commented on templates/blog/top.html
> +					<p>{{ tweet.text }}</p>
を使って改行も反映しましょう

2022-03-20 13:26 UTC, Akinori13 commented on blog/views.py
> +class TweetDelete(DeleteView, LoginRequiredMixin):
優先的にLoginRequiredMixinを継承します
```suggestion
class TweetDelete(LoginRequiredMixin, DeleteView,):

```

2022-03-20 13:26 UTC, Akinori13 commented on blog/views.py
> +class TweetDelete(DeleteView, LoginRequiredMixin):
削除を誰でも出来てしまいますので、バリデーションを挟んでください

2022-03-20 13:26 UTC, Akinori13 commented on blog/views.py
> +    return render(self.request, 'blog/tweet.html', {'form': form})
必要ですか

2022-03-20 13:26 UTC, Akinori13 commented on blog/tests/test_views.py
> +class LoginTweetTests(TestCase):
CreateとDeleteで分けてください！
メソッド名はグリーンテストかレッドテストか明確にするために、successとfailuerを含めてください

2022-03-20 13:26 UTC, Akinori13 commented on blog/tests/test_views.py
> +    self.response_top = self.client.get(self.top_url)
requestを送るのはそれぞれのテストメソッド内でお願いします

2022-03-20 13:26 UTC, Akinori13 commented on blog/tests/test_views.py
> +class LoginTweetTests(TestCase):
- 存在しないTweetに対して削除リクエストを送信する。
- 別のユーザーが作成したTweetに対して削除リクエストを送信する。
- contentが長すぎるデータで作成リクエストを送信する。

2022-03-20 13:26 UTC, Akinori13 commented on blog/views.py
> +    return render(self.request, 'blog/tweet.html', {'form': form})
必要なかったら消しちゃってください

2022-03-26 03:05 UTC, Akinori13 requested changes
いくつかコメントしました

2022-03-26 03:05 UTC, Akinori13 commented on blog/tests/test_views.py
> +    self.login_redirect_url = '/accounts/login/?next=/blog/tweet/'
一例ですが、LOGIN_URLが変更された場合に備えて、以下のようにするといいでしょう。

paramsには、urlencode()を用いましょう

```suggestion
    self.login_redirect_url = f'{reverse(settings.LOGIN_URL)}?{params}'

```

2022-03-26 03:05 UTC, Akinori13 commented on blog/tests/test_views.py
> +    self.login_url = reverse('accounts:login')
設定からLOGIN_URLを読み込む

2022-03-26 03:05 UTC, Akinori13 commented on blog/tests/test_views.py
> +  def test_failure_form_empty(self):
DBに登録されていないかのチェックも

2022-03-26 03:05 UTC, Akinori13 commented on blog/tests/test_views.py
> +  def test_failure_form_empty(self):
他のメソッドにも必要なら追加してください

2022-03-31 06:11 UTC, Akinori13 requested changes
一点コメントしました

2022-03-31 06:11 UTC, Akinori13 commented on blog/tests/test_views.py
> +    self.assertQuerysetEqual(self.response_top.context['object_list'], [])
一例ですが、`self.assertFalse(User.objects.filter(username='example').exists())`

2022-04-01 10:12 UTC, Akinori13 approved these changes

2022-04-01 10:13 UTC, Akinori13 commented
LGTM
メソッド内でも処理がある程度の範囲でまとめられるなら、まとめて、途中で空行を挟んだ方が可読性が上がると思います

2022-04-01 10:13 UTC, merged